### ISSUE TITLE
Could our system support flash based scanning method, solid-state lidar?

### ISSUE THREAD

**Issue by narutojxl** [tiev-tongji/LOG-LIO2#1]
Hello authors, 
Thanks for your excellent work and sharing to community firstly!
Solid state LiDAR has non-uniform angular resolution distribution within the limited horizontal and vertical FOV. Does LOG-LIO2 also like LOG-LIO must need to normal estimate,  Preprocess::estimateNormals(), like [RingFalsNormal](https://github.com/tiev-tongji/RingFalsNormal). Before reading paper details, Could i try our system with a solid-state lidar, thanks in advance!

**Comment by h-k8888** [comment]
LOG-LIO is not available for solid-state lidar right now, because the RingFALS method is designed for spinning lidar. 
We will try to adapt it to solid-state lidar later.

To run solid-state lidar with our code, you need to change the method for normal estimation or comment out the code corresponding to normal estimation and roughness uncertainty.

**Comment by narutojxl** [comment]
Thanks for author kind  reply :)
